### ISSUE TITLE
Is there a way to extend SAM2 to be able to handle live stream? i.e. video frames that it hasn't seen before?

### ISSUE THREAD

**Issue by qdrk** [facebookresearch/sam2#134]
Right now when calling `init_state` on the predictor, you have to specify the directory containing all video frames you'll track, but in the case of livestream, this is not possible, as the frames come in as time goes by. Is there a way to add new frames to the predictor and call `propagate_in_video` with the new frames?

**Comment by Gy920** [comment]
#90  might be helpful to you.
