### ISSUE TITLE
Question about  Zero-shot image tasks

### ISSUE THREAD

**Issue by 1170300714** [facebookresearch/sam2#320]
Thanks for your great work!

I have a question about the zero-shot image tasks.

Since the SAM-2 will predict three mask for each-time forward,  which mask was used to calculate the mIoU in the table results (\eg, Tab 6 )? By default, is the mask with the highest score selected?

 Looking forward to your reply~ Thanks a lot

**Comment by ronghanghu** [comment]
> Since the SAM-2 will predict three mask for each-time forward, which mask was used to calculate the mIoU in the table results (\eg, Tab 6 )? By default, is the mask with the highest score selected?

Yes, the predicted mask with the highest predicted IoU score is selected.
