### ISSUE TITLE
Web framework recommendations for drawing masks on video similar to the demo

### ISSUE THREAD

**Issue by albertjo** [facebookresearch/sam2#328]
Hey guys, what frameworks/technologies do you recommend for drawing masks similar to the demo? After calling SAM2, I've been creating a <canvas> overlay on top of my video - but this is super slow. I'm curious how the demo is able to be so smooth

**Comment by heyoeyo** [comment]
There was another user posting about a web interface (see issue #289) and they seem to be using react.

The demo uses a server to run the SAM model and just gives you back the mask result, as far as I can tell. So your own computer only needs to draw/overlay the masks when using the demo, while the server handles the heavy lifting, which is probably why it's a smoother experience.

**Comment by ronghanghu** [comment]
Hi @albertjo @heyoeyo we have just released our frontend + backend web demo code. Please check it out at https://github.com/facebookresearch/sam2/tree/main/demo
