### ISSUE TITLE
The experimental results of the paper cannot be reproduced

### ISSUE THREAD

**Issue by mr-mating** [facebookresearch/sam2#330]
I installed the official configuration and tested all sizes of sam2 models on datasets such as DAVIS2017, but the J&F values obtained were all smaller than the paper results, why?
![73b02ca178e939e512aab5062ca4d455_compress](https://github.com/user-attachments/assets/7becce3f-b5c7-4841-bfdd-78e5bbabb4fb)

**Comment by GoldenFishes** [comment]
This is very common.

**Comment by ronghanghu** [comment]
Hi @mr-mating, the released checkpoints are those trained without using open-source datasets (like MOSE) to be compliant with the Apache 2.0 release license. Their performance is listed in Table 17 as the highlighted rows below and also listed in the Model Description of this repo at https://github.com/facebookresearch/sam2?tab=readme-ov-file#model-description.

![Screenshot 2024-09-30 231136](https://github.com/user-attachments/assets/9b6fb24e-0173-4fb6-9b2d-466d4d5e2240)

**Comment by ronghanghu** [comment]
@mr-mating Also, we have just provided training and fine-tuning code for SAM 2 in https://github.com/facebookresearch/sam2/tree/main/training. In case you're interested in training on your own datasets, you can use the provided toolkit to train SAM 2
