### ISSUE TITLE
Frame number does't match (before and after SAM2)

### ISSUE THREAD

**Issue by luminousking** [facebookresearch/sam2#331]
Hi, for my personal dataset, I create a mp4 file for 50 frames, however, after I run SAM2 demo on website, I can only extract 40 frames for the SAM2 output. Will SAM2 impact the number of frames? thx

**Comment by GoldenFishes** [comment]
You can manually set the frame rate, just run SAM2 locally.

**Comment by ronghanghu** [comment]
Hi @luminousking, in the demo website, we clipped the video lengths to ensure that it can be rendered in the browser. You may run SAM 2 locally using the video predictor notebook (https://github.com/facebookresearch/sam2/blob/main/notebooks/video_predictor_example.ipynb) to run on your own videos locally

**Comment by AfrifaEben7** [comment]
@ronghanghu I am running the demo locally. When I download the mask, it gives me only one frame. Only a frame but the video seems to be play but when I try to extrate frames, I only get one.

https://github.com/user-attachments/assets/979905ae-f9ae-429d-b8e9-5450568f8eae
