### ISSUE TITLE
TypeError: SAM2Base._encode_new_memory() missing 1 required positional argument: 'object_score_logits'

### ISSUE THREAD

**Issue by antonagafonov** [facebookresearch/sam2#336]
Hi,
I think the last update changed something in sam2_camera_predictor.py

**Comment by ronghanghu** [comment]
Hi @antonagafonov, this `sam2_camera_predictor.py` file is not provided by us in this repo, and is likely provided by a 3rd party. Please contact them to update the codebase.

(\Also, if you are using the previous SAM 2 checkpoints released on July 29, 2024, then as a quick fix, you may add `object_score_logits=None` when calling `_encode_new_memory`
