### ISSUE TITLE
SAM 2.1 Model Loading Error (Unexpected key(s) in state_dict)

### ISSUE THREAD

**Issue by HarryWangATX** [facebookresearch/sam2#337]
I currently am trying to use the SAM2.1 models. I downloaded the `sam2.1_hiera_large.pt` and pasted in the `sam2.1_hiera_l.yaml` config file. However, when I am getting the predictor with `predictor = SAM2ImagePredictor(build_sam2(model_cfg, checkpoint))`. I am getting the following error:

```
RuntimeError: Error(s) in loading state_dict for SAM2Base:
        Unexpected key(s) in state_dict: "no_obj_embed_spatial", "obj_ptr_tpos_proj.weight", "obj_ptr_tpos_proj.bias". 
```

Has anyone encountered/know how to solve this error? Thanks!

**Comment by ronghanghu** [comment]
Hi @HarryWangATX, have you also pulled the latest code from the repo? The SAM 2.1 checkpoints also require using the latest code in this repository.

**Comment by wooferclaw** [comment]
Same issue for me - using code from latest _main_, trying to use **sam2.1_hiera_small** with corresponding yaml, 

Commit ref from my Pipfile.lock
```
        "sam-2": {
            "git": "https://github.com/facebookresearch/segment-anything-2.git",
            "ref": "429a2c736032d38af679049a0c76bd962e51cb3c"
        },
```

**Comment by HarryWangATX** [comment]
Hi @ronghanghu,

Thanks for the help! I have pulled the latest change from the repo and reinstalled my package. However, my code is still running into the same problem. I have diff checked my `sam2_base.py` file with the one hosted on this repository and there were no differences.

**Comment by ronghanghu** [comment]
@HarryWangATX This is weird and I don't have an immediate explanation. To help figure out the issue, could you check the following?
* Could you confirm that you're using the new config file for `sam2.1_hiera_l.yaml` in , which contains the line `no_obj_embed_spatial: true`? (It should have this line if it's correctly setup)
* In your local `sam2_base.py` file (the path from `from sam2.modeling import sam2_base; print(sam2_base.__file__)`), could you try adding a line `assert no_obj_embed_spatial` before this line
https://github.com/facebookresearch/sam2/blob/05d9e57fb3945b10c861046c1e6749e2bfc258e3/sam2/modeling/sam2_base.py#L177 and see if the assertion fails in your model initialization? (The assertion should not fail if it's correctly setup)

**Comment by HarryWangATX** [comment]
Hi @ronghanghu , thank you for the help! I have resolved the issue. Turns out after I installed, it did not update the config files for me, so I was still using the old config files. I copied in the new ones, and it runs now.

**Comment by sjk7524068** [comment]
@HarryWangATX I encountered a same problem , what do you mean by "copied in the new ones", where can I get this new file ?
