### ISSUE TITLE
The package name "SAM 2" is not a valid python package name and may cause problems with `pip`

### ISSUE THREAD

**Issue by MichaelFishmanBDAII** [facebookresearch/sam2#339]
## Observation

I am able to install the package via `pip install git+https://github.com/facebookresearch/segment-anything-2.git`, but I experienced the following problems:

1. `pip list` does not show the package
2. Re-installing the package via `pip install git+https://github.com/facebookresearch/segment-anything-2.git@05d9e57fb3945b10c861046c1e6749e2bfc258e3` didn't update my site-packages.
3. Neither `pip uninstall sam2` nor `pip uninstall "SAM 2"` recognizes the package, so I needed to uninstall it manually via `rm -rf site-packages/sam2`.

## Diagnosis

Python package names [should not include spaces](https://packaging.python.org/en/latest/specifications/name-normalization/#name-format).

The current name in `setup.py` is "SAM 2".

## Proposed solution

Rename it to "sam2", or anything else matching the name regex:

```
^([A-Z0-9]|[A-Z0-9][A-Z0-9._-]*[A-Z0-9])$
```

## PS: Thanks for creating and publishing this work! It's very cool.

**Comment by ronghanghu** [comment]
Thanks for the feedback! The current package name after pip-install will be `SAM-2`
> Neither pip uninstall sam2 nor pip uninstall "SAM 2" recognizes the package, so I needed to uninstall it manually via rm -rf site-packages/sam2.

For now, you can uninstall via `pip uninstall "SAM-2"`

**Comment by MichaelFishmanBDAII** [comment]
Thank you!
