### ISSUE TITLE
Problem with Config .yaml file 

### ISSUE THREAD

**Issue by sahal-786** [facebookresearch/sam2#372]
**I am using the sam2 for images for training as well as for inference for training i update the moos yaml file and also tick mark all the requirements for the training and inference but it give me this error for both.**

python train.py --config sam2.1_hiera_b+_MOSE_finetune
Traceback (most recent call last):
  File "/home/sahal/sam2/training/train.py", line 270, in <module>
    main(args)
  File "/home/sahal/sam2/training/train.py", line 124, in main
    cfg = compose(config_name=args.config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/compose.py", line 38, in compose
    cfg = gh.hydra.compose_config(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/config_loader_impl.py", line 142, in load_configuration
    return self._load_configuration_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/config_loader_impl.py", line 253, in _load_configuration_impl
    defaults_list = create_defaults_list(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 745, in create_defaults_list
    defaults, tree = _create_defaults_list(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 715, in _create_defaults_list
    defaults_tree = _create_defaults_tree(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 356, in _create_defaults_tree
    ret = _create_defaults_tree_impl(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 457, in _create_defaults_tree_impl
    return _expand_virtual_root(repo, root, overrides, skip_missing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 280, in _expand_virtual_root
    subtree = _create_defaults_tree_impl(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 464, in _create_defaults_tree_impl
    config_not_found_error(repo=repo, tree=root)
  File "/home/sahal/sam2/senv/lib/python3.12/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: Cannot find primary config 'sam2.1_hiera_b+_MOSE_finetune'. Check that it's in your config search path.

Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=pkg://sam2
        provider=schema, path=structured://

**Comment by mohwald** [comment]
I encountered similar issue with all sam2.1* models, but sam2* can be loaded just fine. @sahal-786 you can try to move your config to sam2/sam2 or try to reinstall the codebase.

**Comment by sahal-786** [comment]
> I encountered similar issue with all sam2.1* models, but sam2* can be loaded just fine. @sahal-786 you can try to move your config to sam2/sam2 or try to reinstall the codebase.

you were inferencing the model or you were training it because is to train the model.

**Comment by ZixinxinWang** [comment]
> I encountered similar issue with all sam2.1* models, but sam2* can be loaded just fine. @sahal-786 you can try to move your config to sam2/sam2 or try to reinstall the codebase.

I tried reinstalling the codebase and I still can't load the config file. I'm wondering if any of my package conflicts.

**Comment by ZixinxinWang** [comment]
> > I encountered similar issue with all sam2.1* models, but sam2* can be loaded just fine. @sahal-786 you can try to move your config to sam2/sam2 or try to reinstall the codebase.
> 
> I tried reinstalling the codebase and I still can't load the config file. I'm wondering if any of my package conflicts.

Now I see why. You need to really dive into sam2/sam2 and strictly follow the sctrcture of :
![1728619110040(1)](https://github.com/user-attachments/assets/74dcd0ab-5282-43c8-9c14-aa3bae0fcb6f)
note that checkpoint = "../checkpoints/sam2.1_hiera_large.pt" there might be a missing dot.

**Comment by haithamkhedr** [comment]
Hi @sahal-786, as @ZixinxinWang mentioned, you should use `configs/sam2.1_training/sam2.1_hiera_b+_MOSE_finetune.yaml` as your config path.

**Comment by lyu-yx** [comment]
Hi @haithamkhedr ,

I am trying to finetune sam2.1 in custom dataset, but the config file is only valid for `sam2.1_hiera_b+_MOSE_finetune.yaml` even `sam2.1_hiera_b+_custom_finetune.yaml` is put in the same folder as well.(with hydra.errors.MissingConfigException: Cannot find primary config 'configs/sam2.1_training/sam2.1_hiera_b+_VCOD_finetune.yaml'. Check that it's in your config search path.) And it is also interesting that if I paste the cotent in `sam2.1_hiera_b+_custom_finetune.yaml` to `sam2.1_hiera_b+_MOSE_finetune.yaml`, it can exacuate with no error? Seems the yaml file name is the only influence factor and  I am really confused about it.

**Comment by bhack** [comment]
@lyu-yx try `export PYTHONPATH=$PYTHONPATH:/<your-git-checkout-dir>/`

**Comment by seandkim** [comment]
The tutorial is a bit confusing. When you're using sam2 in your own project folder, modify only the checkpoint file path and not the config. 

```python
sam2_checkpoint = "<SOME_RELATIVE_PATH>/checkpoints/sam2.1_hiera_large.pt" # relative path from where you're running your python code
model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml" # do not touch this value
```

**Comment by hiyyg** [comment]
It does not work

> The tutorial is a bit confusing. When you're using sam2 in your own project folder, modify only the checkpoint file path and not the config. I copied checkpoint files into my project folder to make it work.
> 
> ```python
> sam2_checkpoint = "<SOME_RELATIVE_PATH>/checkpoints/sam2.1_hiera_large.pt" # relative path from where you're running your python code
> model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml" # do not touch this value
> ```

**Comment by FurkanGozukara** [comment]
I am giving direct path but still failing why i cant make sense

https://github.com/facebookresearch/sam2/issues/544

**Comment by Provemj** [comment]
just turn the absolute directory to a relative directory, the read-in directory code will turn all input dir into a relative dir
