### ISSUE TITLE
Error locating target 'sam2.modeling.backbones.hieradet.Hiera' ？

### ISSUE THREAD

**Issue by juntaosun** [facebookresearch/sam2#380]
`
checkpoint = "./checkpoints/sam2.1_hiera_large.pt"
model_cfg = "configs/sam2.1/sam2.1_hiera_l.yaml"
predictor = SAM2ImagePredictor(build_sam2(model_cfg, checkpoint))

sam2 = build_sam2(model_cfg, checkpoint, device=device, apply_postprocessing=False)

`

hydra.errors.InstantiationException: Error locating target 'sam2.modeling.backbones.hieradet.Hiera', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.image_encoder.trunk

What is this error? Does anyone know a solution? (Windows 11)

**Comment by CAIC-AD** [comment]
Hi, I encountered the same issue. How did you solve it?

**Comment by 2453828936** [comment]
俺也想知道

**Comment by 2453828936** [comment]
俺新建了个环境 , 运行了一下setup.py  .  好了.

**Comment by HadiaIrshad** [comment]
Did anyone solve this ?

**Comment by 0ENZO** [comment]
For those who still encountering the issue, even if you followed INSTALL.md instructions, do a `from sam2.modeling.backbones.hieradet import Hiera` in a python file. 
In my case it did raise the following : `ModuleNotFoundError: No module named 'iopath'` 
So, a simple :  `pip install -U iopath` solved it.

**Comment by Xqq2620xx** [comment]
I encountered the same problem，it is the environment problem，just check if all the required packages in setup.py have been installed，I miss the iopath，after installed，solved it:

“REQUIRED_PACKAGES = [
    "torch>=2.3.1",
    "torchvision>=0.18.1",
    "numpy>=1.24.4",
    "tqdm>=4.66.1",
    "hydra-core>=1.3.2",
    "iopath>=0.1.10",
    "pillow>=9.4.0",
]”
