### ISSUE TITLE
Video Inference time w.r.t. to object number

### ISSUE THREAD

**Issue by heyufan1995** [facebookresearch/sam2#382]
Hi: 
Is it normal that the inference time linearly increases with respect to the object number during tracking (propagate_in_video)? Is there a way to increase the speed?
Thanks

**Comment by ronghanghu** [comment]
Hi @heyufan1995, yes, it's expected that the inference time would roughly increase linearly with respect to the number of objects being tracked, since in SAM 2, each object is tracked independently (and only their image encoder features from the Hiera backbone is shared).

To increase speed, you can try turning on `torch.compile` by setting `compile_image_encoder: True` in the model config, or using a smaller-sized model (e.g. Hiera-B+ instead of Hiera-L).

**Comment by heyufan1995** [comment]
@ronghanghu Thanks for the quick reply. I have another problem. If segmenting multiple object in video at the same time (add_new_points for all objects and propagate_in_video once), the results are substantially worse than segmenting those object one by one (iterate add_new_points +   propagate_in_video for each object in a for loop).  What is the potential cause for this?

**Comment by ronghanghu** [comment]
Hi @heyufan1995, sorry for the late reply on this! For adding new points for all objects in the video and then propagating the annotation once, the current inference pipeline assumes the following: **If a frame receives annotations, all the objects to segment/track are annotated on that frame**, and if an object is not annotated on a specific frame, it's assumed to be not present (e.g. occluded or moved outside the video) in this frame. So it wouldn't work with partial annotations (only annotating a subset of objects).

For example, if one tracks 3 objects A, B, and C, and wants to provide annotations on frames 0, 10, and 20, the "add_new_points for all objects and propagate_in_video once" inference expects that all the three objects A, B, C are annotated (with points or box prompts) on frame 0, 10, and 20, and if e.g. frame 10 doesn't have an annotation for object B, then the model would assume that object B is confirmed to be occluded/invisible on frame 10. This means that it wouldn't work if the user provided annotation only for object A in frame 0 without annotating B and C, if B or C could also appear in frame 0.

This constraint stems from the inference mechanism of "add_new_points for all objects and propagate_in_video once" where all the objects are batched together and their memory banks and annotations need to be homogeneous. In the future, we might release an alternative inference mechanism that is similar to segmenting objects one by one (without requiring annotating all objects on each prompted frame).

**Comment by heyufan1995** [comment]
Thanks so much!
