### ISSUE TITLE
Problem with finetuning SAM2 on own dataset

### ISSUE THREAD

**Issue by hpichlerbio** [facebookresearch/sam2#391]
I am currently trying to finetune SAM2 on my own dataset using the provided scripts, but i´m having some trouble.

First of all, my dataset contains only 150 images with 1- around 50 masks each. I converted everything to the SA-1B format, so I´m using the same exact dataloader as provided in the MOSE finetuning config [here](https://github.com/facebookresearch/sam2/blob/main/sam2/configs/sam2.1_training/sam2.1_hiera_b%2B_MOSE_finetune.yaml).

In the [training README file](https://github.com/facebookresearch/sam2/blob/main/training/README.md) you explain that you recommend A100 GPUS with 80GB. I tried running the training with 8 H100 GPUs with a batch size of 1 and instantly got an CUDA out of memory error. 

Am I doing something wrong? I also tried finetuning the tiny version of the model, but that didn´t help. Is it also maybe possible to freeze some parts of the network? I don´t see, why I would need to finetune the whole network and not only the prompt encoder and mask decoder, especially if i´m not training on videos.

Thank you in advance!

**Comment by 25benjaminli** [comment]
1. Have you tried profiling your code with pytorch to see what the bottleneck is?
2. If your goal is to have more control and knowledge over what's happening during training, you can modify a custom training script like this: https://github.com/sagieppel/fine-tune-train_segment_anything_2_in_60_lines_of_code

**Comment by icekang** [comment]
Could you try reducing the `num_frames` and see if training is still out of memory?

**Comment by hpichlerbio** [comment]
Thanks for the comments! I found the issue. I set `max_num_objects` way too high. Now it´s a lot better

**Comment by GeorgiaA** [comment]
@hpichlerbio How long is it taking you to fine-tune the model? I need to cost up fine-tuning the model based on cloud resource and I'm trying to get an estimated time of how long it would take. Any insight you have would be great. (E.g. which model are you using, what GPU resource are you using, how many images, how many epochs).

**Comment by muhammadalicortech** [comment]
@hpichlerbio How did you convet your dataset into SA-1B dataset?
