### ISSUE TITLE
微调出错

### ISSUE THREAD

**Issue by tututututurana** [facebookresearch/sam2#395]
hydra.errors.InstantiationException: Error locating target 'training.trainer.Trainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: trainer

**Comment by bhack** [comment]
It is https://github.com/pytorch/tensordict/issues/1048

**Comment by zsz00** [comment]
I use pytorch 2.4.1, meet a same error, Do I need to upgrade to tensordict==0.6 and pytorch==2.5 ?

**Comment by bhack** [comment]
https://github.com/facebookresearch/sam2/pull/402

**Comment by zsz00** [comment]
I saw that, I upgrade tensordict to 0.6, need pytorch to 2.5, To solve this problem, pytorch must be upgraded to 2.5 ??

**Comment by bhack** [comment]
They have upgraded the minimal pytorch version in the last tensordict release.

You can manually backport this https://github.com/pytorch/tensordict/pull/1049 if you want to work with pytorch 2.4

**Comment by zsz00** [comment]
Well, I can't do that, so I'll just upgrade pytorch
