### ISSUE TITLE
Segment multiple objects using different number of keypoints

### ISSUE THREAD

**Issue by mzhadigerov** [facebookresearch/sam2#440]
If I want to segment two distinct objects in the same image, for example, and I provide one keypoint for the first object and two keypoints for the second object. Which function should I use and how?

```python
points = [
  [[266.24, 747.0933333333334]], 
  [[505.17333333333335, 750.5066666666667], [457.38666666666666, 615.68]]
]
labels = [[1], [1, 0]]

predictor.set_image_batch([image])

masks, _, _ = predictor.predict_batch(
[np.array(points)],
[np.array(labels)],
box_batch=None,
multitask_output=False
)
```

throws:
```terminal
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

It requires the number of keypoints to be the same across the objects, but what If I provide more/less points to one object over another object?

**Comment by heyoeyo** [comment]
The simplest solution would probably be to run each segmentation separately. Using a loop would generalize to any number of points:
```python
points = [
  [[266.24, 747.0933333333334]], 
  [[505.17333333333335, 750.5066666666667], [457.38666666666666, 615.68]]
]
labels = [[1], [1, 0]]

predictor.set_image(image)

mask_results = []
for obj_points, obj_labels in zip(points, labels):
  obj_mask, _, _ = predictor.predict(
    np.array(obj_points),
    np.array(obj_labels),
    box=None,
    multitask_output=False
  )
  mask_results.append(obj_mask)

# If needed, combine results as if they were batched
masks = np.concatenate(mask_results)
```
This will be slightly slower than processing as a batch, but it's more flexible.

Alternatively, you can pad the inputs so each object uses the same number of points/labels. Using a label value of -1 acts as a [padding point](https://github.com/facebookresearch/sam2/blob/c2ec8e14a185632b0a5d8b161928ceb50197eddc/sam2/modeling/sam/prompt_encoder.py#L96), which should have less of an impact on the results compared to padding with an extra point coordinate. So your inputs would be something like:
```python
points = [
  [[266.24, 747.0933333333334], [0, 0]], 
  [[505.17333333333335, 750.5066666666667], [457.38666666666666, 615.68]]
]
labels = [[1, -1], [1, 0]]
```

**Comment by mzhadigerov** [comment]
Thanks @heyoeyo . I will try

**Comment by mzhadigerov** [comment]
Using padding gives bad results. Here are segmentations on the same image:

 1) With padding 2) Without padding

![image](https://github.com/user-attachments/assets/fc0cb671-c668-4b18-b2e3-8ef639f45ea1)

![image](https://github.com/user-attachments/assets/c09403e6-89c9-4d66-a897-5408e640a3c1)

![image](https://github.com/user-attachments/assets/1e96e553-5dc5-4d4d-929d-2e76c0fbc121)

**Comment by b07611031** [comment]
Hi, thanks for the discussion and the solution shared by @heyoeyo !  
I tried the **padding approach** for batch prediction of multiple objects and it worked well in my case.  
To make it reusable, I wrote a helper function `padd_image_points` based on the idea.  
Sharing here for reference:

```python
import numpy as np

def padd_image_points(points_list, labels_list):
    """
    Pads points and labels for multiple objects so they have equal length.
    
    Args:
        points_list (list of np.ndarray): Each element is an array of shape (N, 2) for object points.
        labels_list (list of np.ndarray): Each element is an array of shape (N,) for object labels.
    
    Returns:
        tuple: (padded_points, padded_labels) as np.ndarray with shape 
               (num_objects, max_points, 2) and (num_objects, max_points).
    """
    max_points = max(len(p) for p in points_list)
    padded_points = []
    padded_labels = []

    for pts, lbls in zip(points_list, labels_list):
        pad_size = max_points - len(pts)
        if pad_size > 0:
            pts_padded = np.pad(pts, ((0, pad_size), (0, 0)), mode='constant', constant_values=0)
            lbls_padded = np.pad(lbls, (0, pad_size), mode='constant', constant_values=-1)
        else:
            pts_padded, lbls_padded = pts, lbls
        padded_points.append(pts_padded)
        padded_labels.append(lbls_padded)

    return np.stack(padded_points), np.stack(padded_labels)
