### ISSUE TITLE
Errors in finding annotations while training SAM2 on custom dataset

### ISSUE THREAD

**Issue by kunalkotkar10** [facebookresearch/sam2#457]
The finetuning on MOSE dataset works as expected, I had to reduce the resulotion to 256 and num_workers to 6 due to computational issues. I have recreated my custom dataset in the same format and copied the sam2.1_hiera_b+_MOSE_finetune.yaml file for my custom yaml as well. 

The code gets stuck before training and gives the following error:
WARNING:root:Loading failed (id=2); Retry 0 with exception: Cannot sample 8 frames from video skc0 as it only has 0 annotated frames.
WARNING:root:Loading failed (id=1); Retry 1 with exception: Cannot sample 8 frames from video skc1 as it only has 0 annotated frames.
WARNING:root:Loading failed (id=0); Retry 2 with exception: Cannot sample 8 frames from video slc0 as it only has 0 annotated frames.

UnboundLocalError: cannot access local variable 'sampled_frms_and_objs' where it is not associated with a value

In the JPEGImages dir, I have a folder sk0, sk1, sk2 which contains the original images and the same format is followed in Annotations folder. The files are named 00000.png and so on and so forth too. 

Update: Didn't notice that the train images need to be in .jpg compulsarily. Converted from png to jpg and it worked.

**Comment by tesimeiyoulaa** [comment]
THanks u a lot . your advice really help me .  Thank u very much
