### ISSUE TITLE
hydra.errors.InstantiationException

### ISSUE THREAD

**Issue by Lirene3329** [facebookresearch/sam2#461]
hydra.errors.InstantiationException: Error in call to target 'sam2.sam2_video_predictor.SAM2VideoPredictor':
TypeError("SAM2Base.__init__() missing 3 required positional arguments: 'image_encoder', 'memory_attention', and 'memory_encoder'")
full_key: model

hi,I have such a problem, how can I solve it?

**Comment by MAXNORM8650** [comment]
Hey @Lirene3329 , How did you resolve this issues?

**Comment by ArmandAlbert** [comment]
I also encountered the same problem, how did you solve it?

**Comment by Lirene3329** [comment]
you can use `pip install tqdm` for test @MAXNORM8650 @ArmandAlbert , my version is 4.67.1
