### ISSUE TITLE
Demo is completely useless

### ISSUE THREAD

**Issue by intermension** [facebookresearch/sam2#469]
https://sam2.metademolab.com/demo

Thought I'd try it out with one of the demo videos. Clicked on the soccer ball and it doesn't recognize nor track it all. I've tried a couple of my own videos and other demo vids and it's completely useless. For the woman with a dog video; it just selects a blotch on the screen. The promo videos all show a single click and trace. In reality it requires multiple points that never line up. You all must be having a laff - I can do better with FFMPEG and rembg.

The demo videos only return about 2seconds as well so really what was the point?

Brave:

![emta_useless](https://github.com/user-attachments/assets/2b9eedad-ad9a-4149-9ee7-7547d5c6ad93)

![emta_useless22](https://github.com/user-attachments/assets/707e446f-84b3-441e-a240-64161f184734)

Firefox:

![fff](https://github.com/user-attachments/assets/a8cf34fa-7060-4b96-9d39-deda06a79613)

https://github.com/user-attachments/assets/f2c5000c-4bb1-4b10-a891-2c619fcaa5ac

**Comment by Zegervg** [comment]
I have the same issue. There's a mismatch between the input video and the masked segmentation. @intermension

**Comment by Zegervg** [comment]
Its fixxed, turned out to be a browser issue

**Comment by raedle** [comment]
@intermension, thank you for taking the time to share your experience with our demo. It sounds like your browser is having some trouble with the video decoding.

To help us better understand what's going on and find a solution, could you please provide some more information? 

Specifically:
* Any error messages that appear in the browser dev tools console ([open dev tools w/ FireFox](https://firefox-source-docs.mozilla.org/devtools-user/))
* Your browser version, OS, and OS version

This will help us narrow down the problem and work towards a fix.

We appreciate your feedback and value your input. It helps us make our product better for everyone.

@Zegervg, thanks for getting back to us! We're glad to hear that you were able to find a solution to your issue. To help others who may be experiencing similar problems, could you please share what fixed the issue for you? Your feedback is invaluable to us, and we appreciate your willingness to help others in the community

**Comment by Zegervg** [comment]
@raedle Ofcourse I'll help you'll. This is due to a browser incompatibility pretty sure. look at issue https://github.com/facebookresearch/sam2/issues/412
