### ISSUE TITLE
Attempted to set the storage of a tensor on device "cpu" to a storage on different device "mps:0"

### ISSUE THREAD

**Issue by byy-yby** [facebookresearch/sam2#487]
**When i use mps or cpu to run the video-predictor code in notebook, everything about picture segment is ok, but when it comes to the video predictor, the code go wrong like this:**

<img width="954" alt="截屏2024-12-12 13 50 30" src="https://github.com/user-attachments/assets/e19e85c2-bf49-49e9-80b1-4ae9087fabed" />
sonthing meet same problem with me?
my device is mbp m4

**Comment by pwaver** [comment]
Same problem.

**Comment by ronghanghu** [comment]
Hi @pwaver @byy-yby thanks for reporting this issue! I made a patch for the MPS device in https://github.com/facebookresearch/sam2/pull/495

**Comment by pwaver** [comment]
Thank you for the fast and accurate fix.

**Comment by byy-yby** [comment]
@pwaver can you solve this problem by just delete the .pin_momeory?, it seems useless for me. interesting

**Comment by pwaver** [comment]
Yes, I solved it by removing .pin_memory() (and then deleting __pychache__). But on the git site it seems this is not pulled into the main distribution so you may just re install sam2.Sent from my iPadOn Dec 16, 2024, at 11:23 AM, byy-yby ***@***.***> wrote:﻿
@pwaver can you solve this problem by just delete the .pin_momeory?, it seems useless for me. interesting

**Comment by ronghanghu** [comment]
> Yes, I solved it by removing .pin_memory() (and then deleting __pychache__). But on the git site it seems this is not pulled into the main distribution so you may just re install sam2.Sent from my iPadOn Dec 16, 2024, at 11:23 AM, byy-yby ***@***.***> wrote:﻿ @pwaver can you solve this problem by just delete the .pin_momeory?, it seems useless for me. interesting —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi @pwaver, please try pulling the latest code -- it's been merged to https://github.com/facebookresearch/sam2/blob/main/sam2/modeling/sam2_base.py in https://github.com/facebookresearch/sam2/commit/2b90b9f5ceec907a1c18123530e92e794ad901a4

**Comment by byy-yby** [comment]
@pwaver @ronghanghu  thank you for your help!  I have solved this problem by delete pychache and reinstall sam2.
