### ISSUE TITLE
Tensors not on same device after 12/11/2024 update

### ISSUE THREAD

**Issue by shiqiliu-67** [facebookresearch/sam2#489]
Hi, I tried the updated sam2 on video prediction. I `set offload_state_to_cpu=True` due to memory limitation. However, there is an error when exicuting `/root/SoM-Track/sam2/sam2_video_predictor.py` line 623, it shows that the Tensors are not on the same device. I manage to solve this by changing line 618 to `pred_masks_per_obj[obj_idx] = pred_masks.to(self.device)`. I'm not sure this this the right way to implement but it resolved the issue.

**Comment by ronghanghu** [comment]
Thanks for surfacing this -- I'll add a patch for it
