### ISSUE TITLE
How to install and configure without using the latest SAM2

### ISSUE THREAD

**Issue by jianghr-shanghaitech** [facebookresearch/sam2#505]
I noticed that the recent updates require CUDA 12.4 and PyTorch 2.5.1. Although I installed PyTorch 2.5.1 with CUDA 11.8, it still throws the error:

"The detected CUDA version (11.8) mismatches the version that was used to compile PyTorch (12.4). Please make sure to use the same CUDA versions."

I believe this might be because the installation process defaults to installing the latest version of PyTorch. However, due to constraints from other projects, I cannot upgrade CUDA 11.8 to 12.4. Could you please guide me on how to set up a SAM2 environment that only requires CUDA 11.8? Thank you!

**Comment by TikaToka** [comment]
Have you solved this problem? I am struggling with same problem :(

**Comment by TikaToka** [comment]
Have you solved the problem? I'm still struggling with this :(

**Comment by jianghr-shanghaitech** [comment]
I have modified the conflicting libraries, haven't come up with a better solution for now.

**Comment by tsrobcvai** [comment]
https://github.com/facebookresearch/sam2/blob/main/INSTALL.md
It won't affect the basic features, if you don't mind.
