### ISSUE TITLE
RuntimeError in loading state_dict for SAM2Base

### ISSUE THREAD

**Issue by giulio333** [facebookresearch/sam2#89]
`segment-anything-2\sam2\modeling\sam\transformer.py:22: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()
Traceback (most recent call last):
  File "c:\Users\utente\Desktop\segment-anything-2\test.py", line 107, in <module>
    sam2_model = build_sam2(model_cfg, sam2_checkpoint, device="cuda")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\utente\Desktop\segment-anything-2\sam2\build_sam.py", line 36, in build_sam2
    _load_checkpoint(model, ckpt_path)
  File "c:\Users\utente\Desktop\segment-anything-2\sam2\build_sam.py", line 82, in _load_checkpoint
    missing_keys, unexpected_keys = model.load_state_dict(sd)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SAM2Base:`

I have cuda 12.1 installed but i get this error

**Comment by linksluckytime** [comment]
> I solved the problem, I had changed the sam2_checkpoint without also updating the model_cfg accordingly.

嗨伙计，可以告诉我具体的操作步骤吗？

**Comment by linksluckytime** [comment]
> I solved the problem, I had changed the sam2_checkpoint without also updating the model_cfg accordingly.

Hi man, can you tell me the specific steps? I'm using comfyui and it prompted me the same error on startup

**Comment by ilhamije** [comment]
Hi @linksluckytime 

I'm just guessing.
Maybe, the solution that not mentioned by @giulio333 is changing the checkpoint version between sam2 and sam2.1 in [checkpoints downloader](https://github.com/facebookresearch/sam2/blob/main/checkpoints/download_ckpts.sh) is self-documenting. We can change the version by comment-uncomment necessary lines. I haven't try it yet, but I will soon.
